# Generated by Django 4.2.25 on 2026-09-24 01:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('fecha_salida', models.DateField()),
                ('fecha_regreso', models.DateField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('cupos', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('tipo_viaje', models.CharField(choices=[('Nacional', 'Nacional'), ('Internacional', 'Internacional'), ('Aventura', 'Aventura'), ('Playa', 'Playa'), ('Cultural', 'Cultural')], max_length=30)),
                ('descripcion', models.TextField(max_length=500)),
            ],
        ),
    ]
