# Generated by Django 4.2.25 on 2026-09-24 03:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agencia', '0002_alter_viaje_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_personas', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_total', models.DecimalField(decimal_places=0, max_digits=12)),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='agencia.viaje')),
            ],
        ),
    ]
