# Generated by Django 4.2.25 on 2026-09-24 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencia', '0003_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='correo',
            field=models.EmailField(default='correo@temporal.cl', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='nombre',
            field=models.CharField(default='Sin RUT', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='rut',
            field=models.CharField(default='Sin RUT', max_length=12),
            preserve_default=False,
        ),
    ]
