# Generated by Django 4.2.25 on 2026-09-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencia', '0004_reserva_correo_reserva_nombre_reserva_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='correo',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='rut',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='tipo_viaje',
            field=models.CharField(choices=[('Nacional', 'Nacional'), ('Internacional', 'Internacional'), ('Aventura', 'Aventura'), ('Playa', 'Playa'), ('Cultural', 'Cultural')], max_length=100),
        ),
    ]
